config/routes.rb
Rails.application.routes.draw do

resources :sessions, only: [:new, :create, :destroy]

resources :users do
  resources :posts
end

root 'home#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index

		@user = User.find(session[:user_id]) if session[:user_id]
		@posts = @user.posts.all if @user
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		@posts = Post.where(user_id: params[:user_id]).all
		@user = User.find(params[:user_id])
	end

	def show
		@post = Post.find(params[:id])
	end

	def new
		@user = User.find(params[:user_id])
		@post = @user.posts.new
	end

	def create
		@user = User.find(params[:user_id])
		@post = @user.posts.new(post_params)
		if @post.save
			flash[:notice] = 'You just posted.'
		else
			flash[:alert] = 'Unable to post.'
		end
		redirect_to user_posts_path @user.id
	end

	def edit
		@user = User.find(params[:user_id])
		@post = @user.posts.find(params[:id])
	end

	def update
		@user = User.find(params[:user_id])
		@post = @user.posts.find(params[:id])
		if @post.update(post_params)
			flash[:notice] = 'Your post is updated.'
		else
			flash[:alert] = 'Unable to update post.'
		end
		redirect_to user_posts_path @post.user.id
	end

	def destroy
		@post = Post.find(params[:id])
		@user = @post.user
		if @post.destroy
			flash[:notice] = 'Post deleted.'
		else
			flash[:alert] = 'Post not deleted.'
		end
		redirect_to user_posts_path @user.id
	end

	private

	def post_params
		params.require(:post).permit(:body)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def create
		@user = User.where(username: params[:username]).first
		if @user && @user.password == params[:password]
			session[:user_id] = @user.id
			flash[:notice] = 'You are signed in.'
			redirect_to	root_path
		else
			flash[:alert] = 'Sign-in not successful.'
			redirect_to root_path
		end
	end

	def new
		
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
		@posts = @user.posts.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			flash[:notice] = 'Welcome to the app.'
			redirect_to user_posts_path @user
		else
			flash[:alert] = 'Count not create new user.'
		end
	end

	def edit
		@user = User.find(session[:user_id]) if session[:user_id]
		
	end

	def update
		@user = User.find(session[:user_id]) if session[:user_id]
		if @user.update(user_params)
			flash[:notice] = 'Profile Updated'
			redirect_to user_path @user
		else
			flash[:alert] = 'Profile update unsuccessful.'
		end
	end

	def destroy
		@user = User.find(params[:id])
		if @user.destroy
			session[:user_id] = nil
			flash[:notice] = 'Account deleted.'
		else
			flash[:alert] = 'Account not deleted.'
		end
		redirect_to root_path
	end

	private

	def user_params
		params.require(:user).permit(:username, :email, :password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Welcome <%= @user.username if @user %></h1>

<% if @user %>
	<%= link_to('Post something...', new_user_post_path(@user)) %>
	<%= link_to('Edit Posts', user_posts_path(@user.id)) %>

	<% @posts.each do |p| %>
		<p><%= p.user.username %>: <%= p.body%></p>
	<% end %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App14</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<ul>
		<li><%= link_to 'Home', root_path %></li>
		<% if session[:user_id] %>
			<li><%= link_to 'Profile', user_path(session[:user_id]) %></li>
			<li><%= link_to 'Users', users_path %></li>
			<li><%= link_to('Log Out', session_path(session[:user_id]), method: :delete) %></li>
		<% else %>
			<li><%= link_to 'Sign Up', new_user_path %></li>
			<li><%= link_to 'Sign In', new_session_path %></li>
		<% end %>

	</ul>
		<%= flash[:alert] if flash[:alert] %>
		<%= flash[:notice] if flash[:notice] %>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h2>Edit your post</h2>
<br>
<%= form_for [@user, @post] do |e| %>
	<fieldset>
		<div>
			<%= e.label :body %>
			<%= e.text_field :body %>
		</div>
		<div>
			<%= e.submit %>
		</div>
	</fieldset>

<% end %>

app/views/posts/index.html.erb
<h2>Posts</h2>

<% @posts.each do |p| %>

<p><%= p.body%>: <%= p.created_at %>: 
	<%= link_to('Edit Post', edit_user_post_path(p.user, p)) %>: 
	<%= link_to('Delete Post', user_post_path(p.user, p), method: :delete) %></p>

<% end %>

app/views/posts/new.html.erb
<h2>Make a post</h2>
<br>
<%= form_for [@user, @post] do |e| %>
	<fieldset>
		
		<div>
			<%= e.label :body %>
			<%= e.text_field :body %>
		</div>
		<div>
			<%= e.submit %>
		</div>
	</fieldset>

<% end %>

app/views/posts/show.html.erb
<h1><%= @user.username %>'s Info</h1>
<br>

<%= @user.email %>

app/views/users/edit.html.erb
<h2>Update your account</h2>
<br>
<%= form_for @user do |e| %>
	<fieldset>
		
		<div>
			<%= e.label :username %>
			<%= e.text_field :username %>
		</div>
		<div>
			<%= e.label :email %>
			<%= e.text_field :email %>
		</div>
		<div>
			<%= e.label :password %>
			<%= e.text_field :password %>
		</div>
		<div>
			<%= e.submit %>
		</div>
		<div>
			<%= link_to('Delete Account', user_path(@user), method: :delete) %>
		</div>
	</fieldset>

<% end %>

app/views/users/index.html.erb
<h1>All Users</h1>

<% @users.each do |u| %>
	<%= link_to "#{u.username}", user_path(u) %> 
	<br>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |u| %>
	<%= u.label :username %>
	<%= u.text_field :username %>
	<%= u.label	:email %>
	<%= u.text_field :email %>
	<%= u.label :password %>
	<%= u.text_field :password %>
	<%= u.submit :create %>

<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %>'s Profile</h1>

<% if @user.id == session[:user_id] %>
<%= link_to( 'Update your account.', edit_user_path(@user))%>

<% end %>

<% @posts.each do |p| %>

	<p><%= p.user.username %>: <%= p.body%></p>

<% end %>